### ISSUE TITLE
Rust and Sage Implementation do not hash to the same point on the same input

### ISSUE THREAD

**Issue by drskalman** [zhenfeizhang/indifferentiable-hashing#4]
See: https://github.com/w3f-grants-archive/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/commit/6aefa9c3e2e7e8e47e0b5dad776089e31a2a2269
```
n$ sage Indifferentiable\ hashing\ with\ the\ cost\ of\ one\ exponentiation.sage
FF
======================================================================
FAIL: test_bls12_377_test_vector (__main__.TestIndiffJInvJ0Hash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/skalman/code/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/Indifferentiable hashing with the cost of one exponentiation.sage.py", line 434, in test_bls12_377_test_vector
    assert(X/Z == bls12_377_test_vector[i*_sage_const_2 ] and Y/Z == bls12_377_test_vector[i*_sage_const_2 +_sage_const_1 ])
AssertionError

======================================================================
FAIL: test_bls12_381_test_vector (__main__.TestIndiffJInvJ0Hash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/skalman/code/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/Indifferentiable hashing with the cost of one exponentiation.sage.py", line 420, in test_bls12_381_test_vector
    assert(X/Z == bls12_381_test_vector[i*_sage_const_2 ] and Y/Z == bls12_381_test_vector[i*_sage_const_2 +_sage_const_1 ])
AssertionError

----------------------------------------------------------------------
Ran 2 tests in 13.365s

FAILED (failures=2)
```

**Comment by zhenfeizhang** [comment]
Somewhere within those commitments https://github.com/dishport/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/compare/main...w3f-grants-archive:Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation:main

the y coordinates sign got flipped. It should be fixed with https://github.com/zhenfeizhang/indifferentiable-hashing/commit/2ebfb6f7a8444456e0a8c6ec8f560cbf0fd04de1 now

please use the new test vectors and try again @drskalman

**Comment by drskalman** [comment]
I used the updated test vetors. The test passes for BLS12-377 but they still fails for BLS12-381:
```
======================================================================
FAIL: test_bls12_381_test_vector (__main__.TestIndiffJInvJ0Hash)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/skalman/code/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/Indifferentiable hashing with the cost of one exponentiation.sage.py", line 421, in test_bls12_381_test_vector
    assert(X/Z == bls12_381_test_vector[i*_sage_const_2 ] and Y/Z == bls12_381_test_vector[i*_sage_const_2 +_sage_const_1 ])
AssertionError

----------------------------------------------------------------------
Ran 6 tests in 13.791s

FAILED (failures=1)
```

**Comment by zhenfeizhang** [comment]
It should be fixed now.

**Comment by drskalman** [comment]
Indeed:
```
----------------------------------------------------------------------
Ran 6 tests in 14.782s

OK
```
